-- Directions
vim.api.nvim_set_keymap('', 'c', 'h', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 't', 'j', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 's', 'k', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'r', 'l', { noremap = true, nowait = true })
-- Screen navigation
vim.api.nvim_set_keymap('', 'C', 'H', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'T', 'J', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'S', 'K', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'R', 'L', { noremap = true, nowait = true })
-- Folds
vim.api.nvim_set_keymap('', 'zs', 'zj', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'zt', 'zk', { noremap = true, nowait = true })
-- CTSR fallbacks
vim.api.nvim_set_keymap('', 'j', 't', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'J', 'T', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'l', 'c', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'L', 'C', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'h', 'r', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'H', 'R', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'k', 's', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'K', 'S', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', '[k', '[s', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', ']k', ']s', { noremap = true, nowait = true })
-- Remap w (forward word movement) to é
vim.api.nvim_set_keymap('', 'é', 'w', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'É', 'W', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('o', 'aé', 'aw', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('o', 'aÉ', 'aW', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('o', 'ié', 'iw', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('o', 'iÉ', 'iW', { noremap = true, nowait = true })
-- G disambiguation
vim.api.nvim_set_keymap('', 'gs', 'gk', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'gt', 'gj', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'gb', 'gT', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'gé', 'gt', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'g"', 'g0', { noremap = true, nowait = true })
-- Remap useful in normal mode but hard to type in bépo
vim.api.nvim_set_keymap('n', '.', ':', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('n', ':', '.', { noremap = true, nowait = true })
-- Window control
vim.api.nvim_set_keymap('', 'w', '<C-w>', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'W', '<C-w><C-w>', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'wt', '<C-w>j', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'ws', '<C-w>k', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'wc', '<C-w>h', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'wr', '<C-w>l', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'wd', '<C-w>c', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'wo', '<C-w>s', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'wp', '<C-w>o', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'w<SPACE>', ':split<CR>', { noremap = true, nowait = true })
vim.api.nvim_set_keymap('', 'w<CR>', ':vsplit<CR>', { noremap = true, nowait = true })